/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PhoneEntryIndexRouteImport } from './routes/(PhoneEntry)/index'
import { Route as UploadReportRequestReportIdRouteImport } from './routes/upload-report/$requestReportId'
import { Route as SchedulesIdRouteImport } from './routes/schedules/$id'

const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneEntryIndexRoute = PhoneEntryIndexRouteImport.update({
  id: '/(PhoneEntry)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadReportRequestReportIdRoute =
  UploadReportRequestReportIdRouteImport.update({
    id: '/upload-report/$requestReportId',
    path: '/upload-report/$requestReportId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SchedulesIdRoute = SchedulesIdRouteImport.update({
  id: '/schedules/$id',
  path: '/schedules/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/schedules/$id': typeof SchedulesIdRoute
  '/upload-report/$requestReportId': typeof UploadReportRequestReportIdRoute
  '/': typeof PhoneEntryIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/schedules/$id': typeof SchedulesIdRoute
  '/upload-report/$requestReportId': typeof UploadReportRequestReportIdRoute
  '/': typeof PhoneEntryIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/schedules/$id': typeof SchedulesIdRoute
  '/upload-report/$requestReportId': typeof UploadReportRequestReportIdRoute
  '/(PhoneEntry)/': typeof PhoneEntryIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/schedules/$id'
    | '/upload-report/$requestReportId'
    | '/'
    | '/dashboard'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/schedules/$id'
    | '/upload-report/$requestReportId'
    | '/'
    | '/dashboard'
    | '/register'
  id:
    | '__root__'
    | '/schedules/$id'
    | '/upload-report/$requestReportId'
    | '/(PhoneEntry)/'
    | '/dashboard/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SchedulesIdRoute: typeof SchedulesIdRoute
  UploadReportRequestReportIdRoute: typeof UploadReportRequestReportIdRoute
  PhoneEntryIndexRoute: typeof PhoneEntryIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(PhoneEntry)/': {
      id: '/(PhoneEntry)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PhoneEntryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-report/$requestReportId': {
      id: '/upload-report/$requestReportId'
      path: '/upload-report/$requestReportId'
      fullPath: '/upload-report/$requestReportId'
      preLoaderRoute: typeof UploadReportRequestReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules/$id': {
      id: '/schedules/$id'
      path: '/schedules/$id'
      fullPath: '/schedules/$id'
      preLoaderRoute: typeof SchedulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SchedulesIdRoute: SchedulesIdRoute,
  UploadReportRequestReportIdRoute: UploadReportRequestReportIdRoute,
  PhoneEntryIndexRoute: PhoneEntryIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
