import {
  ArrowRightIcon,
  BellIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CalendarDotsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CheckIcon,
  DotsThreeVerticalIcon,
  EyeIcon,
  EyeSlashIcon,
  FileTextIcon,
  GearIcon,
  HeartIcon,
  InfoIcon,
  MagnifyingGlassIcon,
  PencilSimpleIcon,
  PhoneIcon,
  PlusIcon,
  ShareNetworkIcon,
  ShoppingCartIcon,
  StarIcon,
  TrashSimpleIcon,
  UploadIcon,
  UserIcon,
  WarningIcon,
} from "phosphor-react-native";

export type { Icon } from "phosphor-react-native";

export const Icons = {
  CaretLeft: CaretLeftIcon,
  ArrowRight: ArrowRightIcon,
  Check: CheckIcon,
  Heart: HeartIcon,
  Plus: PlusIcon,
  ShoppingCart: ShoppingCartIcon,
  Star: StarIcon,
  CaretDown: CaretDownIcon,
  Eye: EyeIcon,
  EyeSlash: EyeSlashIcon,
  Search: MagnifyingGlassIcon,
  CalendarDotsIcon: CalendarDotsIcon,
  Pencil: PencilSimpleIcon,
  Trash: TrashSimpleIcon,
  MagnifyingGlass: MagnifyingGlassIcon,
  Info: InfoIcon,
  User: UserIcon,
  Phone: PhoneIcon,
  ShareNetwork: ShareNetworkIcon,
  DotsThreeVertical: DotsThreeVerticalIcon,
  CalendarBlank: CalendarBlankIcon,
  FileText: FileTextIcon,
  Warning: WarningIcon,
  UploadIcon: UploadIcon,
  Bell: BellIcon,
  Gear: GearIcon,
  CalendarCheckIcon: CalendarCheckIcon,
} as const;

export type IconName = keyof typeof Icons;
